version: "3.8"

services:
  node:
    build: .
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app:ro
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sabmus8@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-db:
  pgadmin-data: